export const FORECAST_MONTHS = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "total",
] as const;

export type ForecastMonth = (typeof FORECAST_MONTHS)[number];

export type ForecastRowKind =
  | "title"
  | "year"
  | "monthHeader"
  | "spacer"
  | "sectionHeader"
  | "subsection"
  | "data"
  | "subtotal"
  | "netIncome";

export type ForecastValues = Partial<Record<ForecastMonth, number>>;
export type ForecastFormulas = Partial<Record<ForecastMonth, string>>;

export type ForecastRow = {
  excelRow: number;
  label: string | null;
  kind: ForecastRowKind;
  values: ForecastValues;
  formulas?: ForecastFormulas;
};

export const FORECAST_TITLE = "JULIUS SAMPLE BUDGET FORECAST 2026";
export const FORECAST_YEAR = 2026;

export const FORECAST_MONTH_LABELS: Record<ForecastMonth, string> = {
  january: "JANUARY",
  february: "FEBRUARY",
  march: "MARCH",
  april: "APRIL",
  may: "MAY",
  june: "JUNE",
  july: "JULY",
  august: "AUGUST",
  september: "SEPTEMBER",
  october: "OCTOBER",
  november: "NOVEMBER",
  december: "DECEMBER",
  total: "TOTAL",
};

export function formatForecastCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

export const FORECAST_2026_ROWS: ForecastRow[] = [
  { excelRow: 1, label: FORECAST_TITLE, kind: "title", values: {} },
  { excelRow: 2, label: null, kind: "year", values: { april: 2026 } },
  { excelRow: 3, label: null, kind: "monthHeader", values: {} },
  { excelRow: 4, label: null, kind: "spacer", values: {} },
  { excelRow: 5, label: "INCOME:", kind: "sectionHeader", values: {} },
  { excelRow: 6, label: "PRIMARY", kind: "subsection", values: {} },
  {
    excelRow: 7,
    label: "1ST - 2ND GRADE",
    kind: "data",
    values: {
      august: 13145,
      september: 13145,
      october: 13145,
      november: 13145,
      december: 13145,
      total: 65725,
    },
    formulas: {
      august: "1195*11",
      september: "1195*11",
      total: "SUM(C7:N7)",
    },
  },
  {
    excelRow: 8,
    label: "3RD - 4T GRADE",
    kind: "data",
    values: {
      august: 12045,
      september: 12045,
      october: 12045,
      november: 12045,
      december: 12045,
      total: 60225,
    },
    formulas: {
      august: "1095*11",
      september: "1095*11",
      total: "SUM(C8:N8)",
    },
  },
  {
    excelRow: 9,
    label: "OTHER INCOME",
    kind: "data",
    values: {
      august: 1370,
      september: 1370,
      october: 1370,
      november: 1370,
      december: 1370,
      total: 6850,
    },
    formulas: {
      august: "500+300*29/10",
      september: "500+300*29/10",
    },
  },
  {
    excelRow: 10,
    label: "GRANT",
    kind: "data",
    values: { april: 10000, total: 10000 },
  },
  { excelRow: 11, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 12, label: null, kind: "spacer", values: { total: 0 } },
  {
    excelRow: 13,
    label: null,
    kind: "spacer",
    values: { july: 0 },
    formulas: { july: "SUM(I8:I13)" },
  },
  {
    excelRow: 14,
    label: "TOTAL INCOME",
    kind: "subtotal",
    values: {
      january: 0,
      february: 0,
      march: 0,
      april: 10000,
      may: 0,
      june: 0,
      july: 0,
      august: 26560,
      september: 26560,
      october: 26560,
      november: 26560,
      december: 26560,
      total: 142800,
    },
    formulas: {
      january: "SUM(C7:C13)",
      february: "SUM(D7:D13)",
      september: "SUM(K7:K13)",
      october: "SUM(L7:L13)",
      november: "SUM(M7:M13)",
      december: "SUM(N7:N13)",
      total: "SUM(O7:O13)",
    },
  },
  { excelRow: 15, label: null, kind: "spacer", values: {} },
  { excelRow: 16, label: "EXPENSES:", kind: "sectionHeader", values: {} },
  { excelRow: 17, label: "DIRECT LABOR:", kind: "sectionHeader", values: {} },
  {
    excelRow: 18,
    label: "Salaries -Sage",
    kind: "data",
    values: {
      august: -5000,
      september: -5000,
      october: -5000,
      november: -5000,
      december: -5000,
      total: -25000,
    },
    formulas: { total: "SUM(C18:N18)" },
  },
  {
    excelRow: 19,
    label: "Salaries -Zelinda",
    kind: "data",
    values: {
      august: -4000,
      september: -4000,
      october: -4000,
      november: -4000,
      december: -4000,
      total: -20000,
    },
  },
  {
    excelRow: 20,
    label: "Salaries -Joy",
    kind: "data",
    values: {
      august: -4000,
      september: -4000,
      october: -4000,
      november: -4000,
      december: -4000,
      total: -20000,
    },
  },
  {
    excelRow: 21,
    label: "Salaries - Part Time Teacher",
    kind: "data",
    values: { total: 0 },
  },
  { excelRow: 22, label: null, kind: "spacer", values: {} },
  {
    excelRow: 23,
    label: "     Direct Labor Total",
    kind: "subtotal",
    values: {
      january: 0,
      february: 0,
      march: 0,
      april: 0,
      may: 0,
      june: 0,
      july: 0,
      august: -13000,
      september: -13000,
      october: -13000,
      november: -13000,
      december: -13000,
      total: -65000,
    },
    formulas: {
      january: "SUM(C18:C22)",
      february: "SUM(D18:D22)",
      total: "SUM(O18:O22)",
    },
  },
  { excelRow: 24, label: null, kind: "spacer", values: {} },
  {
    excelRow: 25,
    label: "General & Administrative Expenses:",
    kind: "sectionHeader",
    values: { total: 0 },
  },
  { excelRow: 26, label: "WATER", kind: "data", values: { total: 0 } },
  {
    excelRow: 27,
    label: "ELECTRICITY",
    kind: "data",
    values: {
      august: -150,
      september: -150,
      october: -150,
      november: -150,
      december: -150,
      total: -750,
    },
  },
  {
    excelRow: 28,
    label: "GARDENER",
    kind: "data",
    values: {
      august: -350,
      september: -350,
      october: -350,
      november: -350,
      december: -350,
      total: -1750,
    },
  },
  {
    excelRow: 29,
    label: "OFFICE SUPPLES",
    kind: "data",
    values: {
      august: -2000,
      september: -2000,
      october: -1000,
      november: -1000,
      december: -1000,
      total: -7000,
    },
  },
  {
    excelRow: 30,
    label: "OFFICE FURNITURE-CLASSROOM",
    kind: "data",
    values: { march: -30000, total: -30000 },
  },
  {
    excelRow: 31,
    label: "OFFICE FURNITURE-GARDEN",
    kind: "data",
    values: { april: -5000, total: -5000 },
  },
  {
    excelRow: 32,
    label: "OFFICE EQUIPMENT",
    kind: "data",
    values: { july: -4000, august: -1000, total: -5000 },
  },
  { excelRow: 33, label: "OTHER EXPENSES", kind: "data", values: { total: 0 } },
  {
    excelRow: 34,
    label: "ENTERTAINMENT EXPENSE",
    kind: "data",
    values: { total: 0 },
  },
  { excelRow: 35, label: "MEALS", kind: "data", values: { total: 0 } },
  { excelRow: 36, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 37, label: "TRAVEL", kind: "data", values: { total: 0 } },
  {
    excelRow: 38,
    label: "REPAIRS & MAINTEN -OFFICE EQUIP",
    kind: "data",
    values: { total: 0 },
  },
  {
    excelRow: 39,
    label: "REPAIRS & MAINTEN -RENTAL PLACE",
    kind: "data",
    values: { total: 0 },
  },
  { excelRow: 40, label: "PHONE USAGE", kind: "data", values: { total: 0 } },
  { excelRow: 41, label: "MEDICAL EXPENSE", kind: "data", values: { total: 0 } },
  { excelRow: 42, label: "MEDICAL SUPPLIES", kind: "data", values: { total: 0 } },
  {
    excelRow: 43,
    label: "CAR GAS-SAGE",
    kind: "data",
    values: {
      august: -250,
      september: -250,
      october: -250,
      november: -250,
      december: -250,
      total: -1250,
    },
  },
  {
    excelRow: 44,
    label: "CAR GAS-JULIUS",
    kind: "data",
    values: {
      august: -250,
      september: -250,
      october: -250,
      november: -250,
      december: -250,
      total: -1250,
    },
  },
  { excelRow: 45, label: "CAR MILEAGE", kind: "data", values: { total: 0 } },
  {
    excelRow: 46,
    label: "DEPRECIATION EXPENSE",
    kind: "data",
    values: { total: 0 },
  },
  {
    excelRow: 47,
    label: "CAR REGISTRATION",
    kind: "data",
    values: { total: 0 },
  },
  { excelRow: 48, label: "COMPUTER", kind: "data", values: { total: 0 } },
  {
    excelRow: 49,
    label: "CLEANING SUPPLIES",
    kind: "data",
    values: { total: 0 },
  },
  {
    excelRow: 50,
    label: "DEPRECIATION-OFFICE EQUIP",
    kind: "data",
    values: { total: 0 },
  },
  { excelRow: 51, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 52, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 53, label: null, kind: "spacer", values: { total: 0 } },
  {
    excelRow: 54,
    label: "       Gen & Admin Exp Total",
    kind: "subtotal",
    values: {
      january: 0,
      february: 0,
      march: -30000,
      april: -5000,
      may: 0,
      june: 0,
      july: -4000,
      august: -4000,
      september: -3000,
      october: -2000,
      november: -2000,
      december: -2000,
      total: -52000,
    },
    formulas: {
      january: "SUM(C26:C53)",
      february: "SUM(D26:D53)",
      august: "SUM(J26:J53)",
      september: "SUM(K26:K53)",
      october: "SUM(L26:L53)",
      november: "SUM(M26:M53)",
      december: "SUM(N26:N53)",
    },
  },
  { excelRow: 55, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 56, label: null, kind: "spacer", values: { total: 0 } },
  { excelRow: 57, label: null, kind: "spacer", values: { total: 0 } },
  {
    excelRow: 59,
    label: "TOTAL EXPENSES",
    kind: "subtotal",
    values: {
      january: 0,
      february: 0,
      march: -30000,
      april: -5000,
      may: 0,
      june: 0,
      july: -4000,
      august: -17000,
      september: -16000,
      october: -15000,
      november: -15000,
      december: -15000,
      total: -117000,
    },
    formulas: {
      january: "C54+C23",
      february: "D54+D23",
    },
  },
  {
    excelRow: 62,
    label: "NET INCOME",
    kind: "netIncome",
    values: {
      january: 0,
      february: 0,
      march: -30000,
      april: 5000,
      may: 0,
      june: 0,
      july: -5000,
      august: 9560,
      september: 10560,
      october: 11560,
      november: 11560,
      december: 11560,
      total: 25800,
    },
    formulas: {
      january: "C59+C23+C14",
      february: "D14+D59",
      march: "E14+E59",
      april: "F14+F59",
      may: "G14+G59",
      june: "H14+H59",
      july: "I14+I59",
      august: "J14+J59",
      september: "K14+K59",
      october: "L14+L59",
      november: "M14+M59",
      december: "N14+N59",
      total: "O14+O59",
    },
  },
];
