// Static mock data for admin-2 demo portal

export const MOCK_STUDENTS = [
  { id: 's1',  name: 'Emma Richardson',  age: 7,  grade: '2nd', program: 'school_year', parent: 'Sarah Richardson',   status: 'enrolled',  specialNeeds: false },
  { id: 's2',  name: 'Liam Torres',      age: 9,  grade: '4th', program: 'both',        parent: 'Miguel Torres',      status: 'enrolled',  specialNeeds: false },
  { id: 's3',  name: 'Ava Chen',         age: 6,  grade: '1st', program: 'summer',      parent: 'Jennifer Chen',      status: 'enrolled',  specialNeeds: true  },
  { id: 's4',  name: 'Noah Foster',      age: 5,  grade: 'K',   program: 'summer',      parent: 'Diana Foster',       status: 'enrolled',  specialNeeds: false },
  { id: 's5',  name: 'Sophia Patel',     age: 8,  grade: '3rd', program: 'school_year', parent: 'Priya Patel',        status: 'enrolled',  specialNeeds: false },
  { id: 's6',  name: 'Jackson Kim',      age: 10, grade: '5th', program: 'both',        parent: 'Robert Kim',         status: 'enrolled',  specialNeeds: false },
  { id: 's7',  name: 'Olivia Martinez',  age: 7,  grade: '2nd', program: 'school_year', parent: 'Carlos Martinez',    status: 'enrolled',  specialNeeds: true  },
  { id: 's8',  name: 'Elijah Brooks',    age: 6,  grade: '1st', program: 'summer',      parent: 'Amanda Brooks',      status: 'enrolled',  specialNeeds: false },
  { id: 's9',  name: 'Chloe Nguyen',     age: 9,  grade: '4th', program: 'school_year', parent: 'Lan Nguyen',         status: 'enrolled',  specialNeeds: false },
  { id: 's10', name: 'Mason Wright',     age: 8,  grade: '3rd', program: 'both',        parent: 'David Wright',       status: 'enrolled',  specialNeeds: false },
  { id: 's11', name: 'Isabelle Clarke',  age: 11, grade: '6th', program: 'school_year', parent: 'Stephanie Clarke',   status: 'enrolled',  specialNeeds: false },
  { id: 's12', name: 'Ethan Murphy',     age: 7,  grade: '2nd', program: 'summer',      parent: 'Patricia Murphy',    status: 'enrolled',  specialNeeds: true  },
  { id: 's13', name: 'Mia Johnson',      age: 5,  grade: 'K',   program: 'school_year', parent: 'Kevin Johnson',      status: 'enrolled',  specialNeeds: false },
  { id: 's14', name: 'Lucas Williams',   age: 8,  grade: '3rd', program: 'both',        parent: 'Tara Williams',      status: 'enrolled',  specialNeeds: false },
  { id: 's15', name: 'Harper Davis',     age: 10, grade: '5th', program: 'school_year', parent: 'Mark Davis',         status: 'enrolled',  specialNeeds: false },
  { id: 's16', name: 'Aiden Thompson',   age: 6,  grade: '1st', program: 'summer',      parent: 'Grace Thompson',     status: 'enrolled',  specialNeeds: false },
  { id: 's17', name: 'Aria Robinson',    age: 9,  grade: '4th', program: 'both',        parent: 'Michelle Robinson',  status: 'enrolled',  specialNeeds: false },
  { id: 's18', name: 'Landon Scott',     age: 7,  grade: '2nd', program: 'school_year', parent: 'Brian Scott',        status: 'enrolled',  specialNeeds: true  },
  { id: 's19', name: 'Zoe Harris',       age: 11, grade: '6th', program: 'summer',      parent: 'Linda Harris',       status: 'enrolled',  specialNeeds: false },
  { id: 's20', name: 'Caleb Flores',     age: 8,  grade: '3rd', program: 'school_year', parent: 'Maria Flores',       status: 'enrolled',  specialNeeds: false },
  { id: 's21', name: 'Lily Anderson',    age: 6,  grade: '1st', program: 'both',        parent: 'James Anderson',     status: 'enrolled',  specialNeeds: false },
  { id: 's22', name: 'Owen Jackson',     age: 9,  grade: '4th', program: 'summer',      parent: 'Brenda Jackson',     status: 'enrolled',  specialNeeds: false },
  { id: 's23', name: 'Nora Gonzalez',    age: 5,  grade: 'K',   program: 'school_year', parent: 'Victor Gonzalez',    status: 'enrolled',  specialNeeds: false },
  { id: 's24', name: 'Sebastian Lee',    age: 10, grade: '5th', program: 'both',        parent: 'Angela Lee',         status: 'enrolled',  specialNeeds: true  },
]

export const MOCK_LEADS = [
  { id: 'l1',  type: 'waitlist', parentName: 'Diana Foster',      email: 'diana@email.com',       phone: '(512) 555-0142', childName: 'Noah Foster',    childAge: 5,  status: 'new',          tags: ['summer'],                  createdAt: '2026-03-28', message: null },
  { id: 'l2',  type: 'contact',  parentName: 'Robert Kim',        email: 'rkim@gmail.com',        phone: '(737) 555-0218', childName: null,             childAge: null, status: 'contacted',    tags: ['school_year', 'scholarship'], createdAt: '2026-04-01', message: 'Interested in fall enrollment for my daughter in 3rd grade.' },
  { id: 'l3',  type: 'waitlist', parentName: 'Priya Patel',       email: 'ppatel@email.com',      phone: '(512) 555-0391', childName: 'Raj Patel',      childAge: 7,  status: 'emailed',      tags: ['school_year'],             createdAt: '2026-03-20', message: null },
  { id: 'l4',  type: 'contact',  parentName: 'Mark Sullivan',     email: 'msullivan@email.com',   phone: '(737) 555-0477', childName: null,             childAge: null, status: 'new',          tags: ['summer'],                  createdAt: '2026-04-03', message: 'Looking for summer options for twin boys, ages 7.' },
  { id: 'l5',  type: 'waitlist', parentName: 'Claire Beaumont',   email: 'claire.b@email.com',    phone: '(512) 555-0563', childName: 'Lily Beaumont',  childAge: 6,  status: 'application_sent', tags: ['school_year'],          createdAt: '2026-03-15', message: null },
  { id: 'l6',  type: 'waitlist', parentName: 'Jerome Watkins',    email: 'jwatkins@email.com',    phone: '(737) 555-0649', childName: 'Tyler Watkins',  childAge: 9,  status: 'enrolled',     tags: ['both'],                    createdAt: '2026-02-10', message: null },
  { id: 'l7',  type: 'contact',  parentName: 'Sandra Cho',        email: 'sandcho@email.com',     phone: '(512) 555-0735', childName: null,             childAge: null, status: 'not_contacted', tags: [],                         createdAt: '2026-04-05', message: 'Heard about your school from a friend. What are your rates?' },
  { id: 'l8',  type: 'waitlist', parentName: 'Luis Mendez',       email: 'lmendez@email.com',     phone: '(737) 555-0821', childName: 'Sofia Mendez',   childAge: 8,  status: 'contacted',    tags: ['school_year', 'spanish'],  createdAt: '2026-03-25', message: null },
  { id: 'l9',  type: 'waitlist', parentName: 'Rebecca Stone',     email: 'rstone@email.com',      phone: '(512) 555-0907', childName: 'Owen Stone',     childAge: 5,  status: 'nurture',      tags: ['summer'],                  createdAt: '2026-01-18', message: null },
  { id: 'l10', type: 'contact',  parentName: 'David Park',        email: 'dpark@email.com',       phone: '(737) 555-0093', childName: null,             childAge: null, status: 'new',          tags: ['homeschool'],              createdAt: '2026-04-06', message: 'We homeschool and are looking for social enrichment days.' },
  { id: 'l11', type: 'waitlist', parentName: 'Tiffany Burns',     email: 'tburns@email.com',      phone: '(512) 555-0179', childName: 'Jasmine Burns',  childAge: 10, status: 'enrolled',     tags: ['school_year'],             createdAt: '2026-01-30', message: null },
  { id: 'l12', type: 'contact',  parentName: 'Henry Walsh',       email: 'hwalsh@email.com',      phone: '(737) 555-0265', childName: null,             childAge: null, status: 'on_hold',      tags: ['summer', 'scholarship'],   createdAt: '2026-03-10', message: 'Interested but need financial aid information.' },
  { id: 'l13', type: 'waitlist', parentName: 'Natalie Cruz',      email: 'ncruz@email.com',       phone: '(512) 555-0351', childName: 'Marco Cruz',     childAge: 6,  status: 'contacted',    tags: ['summer'],                  createdAt: '2026-03-22', message: null },
  { id: 'l14', type: 'contact',  parentName: 'Thomas Reed',       email: 'treed@email.com',       phone: '(737) 555-0437', childName: null,             childAge: null, status: 'not_fit',      tags: [],                          createdAt: '2026-02-28', message: 'Wanted to inquire about daycare options.' },
  { id: 'l15', type: 'waitlist', parentName: 'Alicia Hammond',    email: 'ahammond@email.com',    phone: '(512) 555-0523', childName: 'Grace Hammond',  childAge: 7,  status: 'emailed',      tags: ['school_year'],             createdAt: '2026-03-18', message: null },
  { id: 'l16', type: 'waitlist', parentName: 'Kevin Okonkwo',     email: 'kokonkwo@email.com',    phone: '(737) 555-0609', childName: 'Chidera Okonkwo',childAge: 8,  status: 'new',          tags: ['both'],                    createdAt: '2026-04-02', message: null },
  { id: 'l17', type: 'contact',  parentName: 'Jessica Huang',     email: 'jhuang@email.com',      phone: '(512) 555-0695', childName: null,             childAge: null, status: 'application_sent', tags: ['school_year'],         createdAt: '2026-03-30', message: 'Very interested after touring the campus.' },
  { id: 'l18', type: 'waitlist', parentName: 'Marcus Webb',       email: 'mwebb@email.com',       phone: '(737) 555-0781', childName: 'Aiden Webb',     childAge: 5,  status: 'new',          tags: ['summer'],                  createdAt: '2026-04-04', message: null },
  { id: 'l19', type: 'contact',  parentName: 'Stephanie Cole',    email: 'scole@email.com',       phone: '(512) 555-0867', childName: null,             childAge: null, status: 'contacted',    tags: ['school_year'],             createdAt: '2026-03-27', message: 'Follow-up from school fair visit last month.' },
  { id: 'l20', type: 'waitlist', parentName: 'Anthony Ross',      email: 'aross@email.com',       phone: '(737) 555-0953', childName: 'Dani Ross',      childAge: 9,  status: 'lost',         tags: [],                          createdAt: '2026-02-05', message: null },
  { id: 'l21', type: 'waitlist', parentName: 'Carmen Vega',       email: 'cvega@email.com',       phone: '(512) 555-0139', childName: 'Leo Vega',       childAge: 6,  status: 'enrolled',     tags: ['summer'],                  createdAt: '2026-02-14', message: null },
  { id: 'l22', type: 'contact',  parentName: 'Brian Thornton',    email: 'bthornton@email.com',   phone: '(737) 555-0225', childName: null,             childAge: null, status: 'new',          tags: ['both'],                    createdAt: '2026-04-07', message: 'Referred by Emma Richardson\'s family.' },
  { id: 'l23', type: 'waitlist', parentName: 'Linda Nakamura',    email: 'lnakamura@email.com',   phone: '(512) 555-0311', childName: 'Yuki Nakamura',  childAge: 7,  status: 'nurture',      tags: ['school_year'],             createdAt: '2026-01-22', message: null },
  { id: 'l24', type: 'contact',  parentName: 'Gregory Moss',      email: 'gmoss@email.com',       phone: '(737) 555-0397', childName: null,             childAge: null, status: 'contacted',    tags: ['summer', 'scholarship'],   createdAt: '2026-03-29', message: 'Single parent, looking for affordable options.' },
  { id: 'l25', type: 'waitlist', parentName: 'Rachel Simmons',    email: 'rsimmons@email.com',    phone: '(512) 555-0483', childName: 'Kai Simmons',    childAge: 11, status: 'application_submitted', tags: ['school_year'], createdAt: '2026-03-12', message: null },
]

export const MOCK_APPLICATIONS = [
  { id: 'a1',  childName: 'Emma Richardson',   preferredName: null,   age: 7,  grade: '2nd', program: 'school_year_26_27', parent1: 'Sarah Richardson',  parent1Email: 'sarah.r@email.com',  status: 'enrolled',    submittedAt: '2025-11-14' },
  { id: 'a2',  childName: 'Marcus Park',       preferredName: 'Marc', age: 8,  grade: '3rd', program: 'both',              parent1: 'Jason Park',        parent1Email: 'jpark@email.com',    status: 'in_review',   submittedAt: '2026-03-30' },
  { id: 'a3',  childName: 'Sofia Mendez',      preferredName: null,   age: 8,  grade: '3rd', program: 'school_year_26_27', parent1: 'Luis Mendez',       parent1Email: 'lmendez@email.com',  status: 'in_review',   submittedAt: '2026-04-01' },
  { id: 'a4',  childName: 'Liam Torres',       preferredName: null,   age: 9,  grade: '4th', program: 'both',              parent1: 'Miguel Torres',     parent1Email: 'mig.t@email.com',    status: 'enrolled',    submittedAt: '2025-12-03' },
  { id: 'a5',  childName: 'Isabelle Clarke',   preferredName: 'Izzy', age: 11, grade: '6th', program: 'school_year_26_27', parent1: 'Stephanie Clarke',  parent1Email: 'sclarke@email.com',  status: 'enrolling',   submittedAt: '2026-03-18' },
  { id: 'a6',  childName: 'Tyler Watkins',     preferredName: null,   age: 9,  grade: '4th', program: 'both',              parent1: 'Jerome Watkins',    parent1Email: 'jwatkins@email.com', status: 'enrolled',    submittedAt: '2025-12-20' },
  { id: 'a7',  childName: 'Grace Hammond',     preferredName: null,   age: 7,  grade: '2nd', program: 'school_year_26_27', parent1: 'Alicia Hammond',    parent1Email: 'ahammond@email.com', status: 'in_review',   submittedAt: '2026-04-02' },
  { id: 'a8',  childName: 'Chidera Okonkwo',   preferredName: 'Chi',  age: 8,  grade: '3rd', program: 'both',              parent1: 'Kevin Okonkwo',     parent1Email: 'kokonkwo@email.com', status: 'in_progress', submittedAt: '2026-04-04' },
  { id: 'a9',  childName: 'Kai Simmons',       preferredName: null,   age: 11, grade: '6th', program: 'school_year_26_27', parent1: 'Rachel Simmons',    parent1Email: 'rsimmons@email.com', status: 'enrolling',   submittedAt: '2026-03-22' },
  { id: 'a10', childName: 'Noah Foster',       preferredName: null,   age: 5,  grade: 'K',   program: 'summer_26',         parent1: 'Diana Foster',      parent1Email: 'diana@email.com',    status: 'enrolled',    submittedAt: '2026-01-15' },
  { id: 'a11', childName: 'Lily Beaumont',     preferredName: null,   age: 6,  grade: '1st', program: 'school_year_26_27', parent1: 'Claire Beaumont',   parent1Email: 'claire.b@email.com', status: 'in_review',   submittedAt: '2026-04-03' },
  { id: 'a12', childName: 'Yuki Nakamura',     preferredName: null,   age: 7,  grade: '2nd', program: 'school_year_26_27', parent1: 'Linda Nakamura',    parent1Email: 'lnakamura@email.com',status: 'in_progress', submittedAt: '2026-04-06' },
]

export const MOCK_TRANSACTIONS = [
  { id: 't1',  payerName: 'Sarah Richardson',  amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'school_year', method: 'card'   },
  { id: 't2',  payerName: 'Miguel Torres',     amount: 900,  type: 'deposit',      status: 'succeeded', date: '2026-03-29', program: 'both',        method: 'card'   },
  { id: 't3',  payerName: 'Jennifer Chen',     amount: 900,  type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'summer',      method: 'card'   },
  { id: 't4',  payerName: 'Priya Patel',       amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'school_year', method: 'ach'    },
  { id: 't5',  payerName: 'Jerome Watkins',    amount: 500,  type: 'registration', status: 'succeeded', date: '2026-03-25', program: 'both',        method: 'card'   },
  { id: 't6',  payerName: 'Diana Foster',      amount: 900,  type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'summer',      method: 'card'   },
  { id: 't7',  payerName: 'Kevin Johnson',     amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'school_year', method: 'card'   },
  { id: 't8',  payerName: 'Tara Williams',     amount: 900,  type: 'deposit',      status: 'succeeded', date: '2026-03-28', program: 'both',        method: 'card'   },
  { id: 't9',  payerName: 'Mark Davis',        amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'school_year', method: 'card'   },
  { id: 't10', payerName: 'Grace Thompson',    amount: 900,  type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'summer',      method: 'ach'    },
  { id: 't11', payerName: 'Michelle Robinson', amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'both',        method: 'card'   },
  { id: 't12', payerName: 'Amanda Brooks',     amount: 250,  type: 'registration', status: 'succeeded', date: '2026-03-20', program: 'summer',      method: 'card'   },
  { id: 't13', payerName: 'Lan Nguyen',        amount: 1800, type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'school_year', method: 'card'   },
  { id: 't14', payerName: 'David Wright',      amount: 900,  type: 'tuition',      status: 'processing',date: '2026-04-05', program: 'both',        method: 'ach'    },
  { id: 't15', payerName: 'Stephanie Clarke',  amount: 1800, type: 'deposit',      status: 'succeeded', date: '2026-03-22', program: 'school_year', method: 'card'   },
  { id: 't16', payerName: 'Patricia Murphy',   amount: 900,  type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'summer',      method: 'card'   },
  { id: 't17', payerName: 'Carmen Vega',       amount: 900,  type: 'tuition',      status: 'succeeded', date: '2026-04-01', program: 'summer',      method: 'card'   },
  { id: 't18', payerName: 'Angela Lee',        amount: 1800, type: 'tuition',      status: 'failed',    date: '2026-04-02', program: 'both',        method: 'card'   },
]

export const MOCK_MONTHLY_REVENUE = [
  { month: 'May 25',  revenue: 3200,  expenses: 2800 },
  { month: 'Jun 25',  revenue: 8400,  expenses: 4100 },
  { month: 'Jul 25',  revenue: 9200,  expenses: 4300 },
  { month: 'Aug 25',  revenue: 7100,  expenses: 5200 },
  { month: 'Sep 25',  revenue: 9800,  expenses: 5400 },
  { month: 'Oct 25',  revenue: 10200, expenses: 5500 },
  { month: 'Nov 25',  revenue: 9600,  expenses: 5200 },
  { month: 'Dec 25',  revenue: 5800,  expenses: 3200 },
  { month: 'Jan 26',  revenue: 9400,  expenses: 5300 },
  { month: 'Feb 26',  revenue: 9600,  expenses: 5400 },
  { month: 'Mar 26',  revenue: 9800,  expenses: 5500 },
  { month: 'Apr 26',  revenue: 4200,  expenses: 2600 },
]

export const MOCK_ACTIVITY = [
  { id: 'ev1',  type: 'application', text: 'New application from Emma R.',       time: '2m ago',  color: 'purple'  },
  { id: 'ev2',  type: 'payment',     text: 'Payment received — $1,800 tuition',  time: '15m ago', color: 'success' },
  { id: 'ev3',  type: 'lead',        text: 'New waitlist signup — Noah Foster',  time: '1h ago',  color: 'info'    },
  { id: 'ev4',  type: 'approved',    text: 'Application approved — Isabelle C.', time: '3h ago',  color: 'success' },
  { id: 'ev5',  type: 'payment',     text: 'Payment received — $900 summer',     time: '4h ago',  color: 'success' },
  { id: 'ev6',  type: 'lead',        text: 'Contact form — Brian Thornton',      time: '6h ago',  color: 'info'    },
  { id: 'ev7',  type: 'tour',        text: 'Tour scheduled — Park family',       time: '1d ago',  color: 'warning' },
  { id: 'ev8',  type: 'enrolled',    text: 'Enrolled — Tyler W. (both programs)', time: '2d ago', color: 'success' },
]

export const MOCK_PROGRAMS = [
  {
    id: 'summer_26',
    name: 'Summer 2026',
    season: 'Summer',
    startDate: '2026-05-26',
    endDate: '2026-07-31',
    capacity: 20,
    enrolled: 18,
    waitlist: 6,
    tuitionMonthly: 900,
    tuitionFull: 1800,
    revenue: 16200,
    status: 'active',
  },
  {
    id: 'school_year_26_27',
    name: 'School Year 2026–27',
    season: 'Annual',
    startDate: '2026-09-08',
    endDate: '2027-05-22',
    capacity: 22,
    enrolled: 14,
    waitlist: 3,
    tuitionMonthly: 1800,
    tuitionFull: 18000,
    revenue: 25200,
    status: 'enrolling',
  },
]

export const MOCK_EVENTS = [
  { id: 'c1', title: 'Summer Program Orientation',     date: '2026-05-20', type: 'event',    program: 'summer'      },
  { id: 'c2', title: 'Q2 Parent Newsletter Deadline',  date: '2026-04-15', type: 'deadline', program: null          },
  { id: 'c3', title: 'Staff Planning Meeting',          date: '2026-04-11', type: 'internal', program: null          },
  { id: 'c4', title: 'School Year Enrollment Closes',  date: '2026-04-30', type: 'deadline', program: 'school_year' },
  { id: 'c5', title: 'Campus Family Open Day',         date: '2026-04-18', type: 'event',    program: null          },
]
